package com.finitas.financemanagerstore.config

enum class ErrorCode {
    FINISHED_SPENDING_NOT_FOUND,
    FINISHED_SPENDING_EXISTS,
    FINISHED_SPENDING_DELETED,
    SHOPPING_LIST_NOT_FOUND,
    SHOPPING_LIST_EXISTS,
    SHOPPING_LIST_DELETED,
    USER_NOT_FOUND,
    STORE_REQUEST_INPUT_INVALID,
}