package com.finitas.financemanagerstore.config

enum class ErrorCode {
    FINISHED_SPENDING_NOT_FOUND,
    FINISHED_SPENDING_EXISTS,
    SHOPPING_LIST_NOT_FOUND,
    SHOPPING_LIST_EXISTS,
    USER_NOT_FOUND,
    STORE_REQUEST_INPUT_VALIDATION_FAILED,
    STORE_REQUEST_NON_PARSABLE,
}